IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[dogOwners]'))
BEGIN
  CREATE TABLE [dbo].[dogOwners] (
  [NAME] NCHAR(100),
  [DOGNAME] NCHAR(100),
  [EMAIL] NCHAR(100) NOT NULL PRIMARY KEY,
  [TOWN] NCHAR(100),
  [POSTCODE] NCHAR(100)
  );
END;